// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-yXRW_AYU7caml0LJFRfJeXhaya_urs',
    appId: '1:12635195197:web:0928be881f2e4455ac2754',
    messagingSenderId: '12635195197',
    projectId: 'enadmohammed-84875',
    authDomain: 'enadmohammed-84875.firebaseapp.com',
    storageBucket: 'enadmohammed-84875.firebasestorage.app',
    measurementId: 'G-61C0DX4S4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6Voj4ISHYmH6aULbKm_ByWU2_tCjllM',
    appId: '1:12635195197:android:dafb3b034aee8b29ac2754',
    messagingSenderId: '12635195197',
    projectId: 'enadmohammed-84875',
    storageBucket: 'enadmohammed-84875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbD_poM3NQ46_hJkAjGB_V5Z1RIvhPRZQ',
    appId: '1:12635195197:ios:581afd48676ea948ac2754',
    messagingSenderId: '12635195197',
    projectId: 'enadmohammed-84875',
    storageBucket: 'enadmohammed-84875.firebasestorage.app',
    iosBundleId: 'com.example.adminNotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbD_poM3NQ46_hJkAjGB_V5Z1RIvhPRZQ',
    appId: '1:12635195197:ios:581afd48676ea948ac2754',
    messagingSenderId: '12635195197',
    projectId: 'enadmohammed-84875',
    storageBucket: 'enadmohammed-84875.firebasestorage.app',
    iosBundleId: 'com.example.adminNotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-yXRW_AYU7caml0LJFRfJeXhaya_urs',
    appId: '1:12635195197:web:d8c7918bf66a4fe8ac2754',
    messagingSenderId: '12635195197',
    projectId: 'enadmohammed-84875',
    authDomain: 'enadmohammed-84875.firebaseapp.com',
    storageBucket: 'enadmohammed-84875.firebasestorage.app',
    measurementId: 'G-FE7X40VDLE',
  );
}
